language: python
python:
  - "2.7"
services:
  - mongodb
install:
  - "pip install pip8 Flask Flask-Login Flask-Bcrypt Flask-SeaSurf Flask-Cache Flask-Admin pymongo mongokit Flask-MongoKit blinker PyYAML pygments --use-mirrors"
script: 
  - "pep8 --repeat src/"
